version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Run bundle install
          command: bundle install

      - run:
          name: Audit code with robocop
          command: rubocop -l

      - run:
          name: Audit the gemfile
          command: bundle-audit check

      - run:
          name: Deploy Master to heroku
          command: git push https://git.heroku.com/evening-refuge-40256.git master

